#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" API call
    This script executes the call to the Hitouch API called ReRAPI
    
    Created on Thu Mar 28 2020
    Authors:    Daniel Laumer (laumerd@ethz.ch)
                Haojun Cai (caihao@ethz.ch)
    
"""

import requests # To open URL adresses
import json

import help_functions as hlp


def getResponse(url, data=None):
    if data is None: 
        response = requests.ppst(url)  # Get the response 
    else:
        response = requests.post(url, data = data)  # Get the response 
    return response.text

def readFile(path):
    with open(path, 'r') as file:
        data = file.read()
    return data

#%% Set variables: 
urlCore = 'https://renderingapi.azurewebsites.net/api/'
userId = ""
gpxFiles = ['Daniel_11','Daniel_13','Daniel_242','Daniel_350']

#%% 1. Intialise and get importID
urlInit = urlCore + 'initimport'
importID = getResponse(urlInit)

#%% 2. Upload GPX files

urlImport = urlCore + 'import/' + importID
gpsFileIds = []
for gpxFile in gpxFiles:
    fileContent = readFile('../gpxAPI/' + gpxFile + '.gpx')
    gpsFileIds.append(getResponse(urlImport, fileContent))

aeFile = readFile('../VerticalID.json')
aeFileId = getResponse(urlImport, aeFile)


#%% 3. Prepare service call file (sc.json)
scParam = {}
scParam['UserId'] = userId
scParam['RefGpx'] = gpsFileIds
scParam['RefAutomationSettings'] = aeFileId
scParam['NetworkName'] = "Import Network Example"
scParam['CompilationName'] = "Group #1"
scParam['ScenarioName']  = "RerApi Scenario #1"

scFile = json.dumps(scParam)

#%% 4. Import
urlExecute = urlCore + 'import/' + importID + '/execute'
networkId = getResponse(urlExecute, scFile)